### ISSUE TITLE
Scrolling CodeListView when InputEdit is active

### ISSUE THREAD

**Issue by danil-kondr2016** [kodemeister/X584#16] opened 2024-10-11 12:18 UTC
On Windows 11, if user had not turned off scrolling unfocused windows, CodeListView will be scrolled even if InputEdit is active.

**Comment by kodemeister** [comment] 2024-10-12 10:46
There is actually a simpler way to reproduce this issue. Just click anywhere in the comment column to start editing and then use horizontal or vertical scrollbars. The `InputEdit` won't disappear during scrolling.

This issue seems to be introduced in commit 514aaa51ee6a44099aac5e5055adf41ec018e803. I guess the line `InputEditExit(this);` was added by purpose to the original code. If user tried to scroll the code list view, repainting was triggered and comment editing was finished.

Can we somehow detect scrolling events and call `InputEditExit(this);` automatically?

**Comment by danil-kondr2016** [comment] 2024-10-12 11:24
I haven't found way to catch events of scrolling CodeListView so I propose following way to detect scrolling:
1. When starting editing, save top item
2. In `CodeListViewCustomDrawItem` if top item is not the same as fixed one `InputEditExit(this);`

**Comment by danil-kondr2016** [comment] 2024-10-12 11:30
I tried to implement this way but I have introduced a new bug: edited item won't draw on screen until activated

**Comment by danil-kondr2016** [comment] 2024-10-12 11:44
> I haven't found way to catch events of scrolling CodeListView so I propose following way to detect scrolling:
> 
> 1. When starting editing, save top item
> 2. In `CodeListViewCustomDrawItem` if top item is not the same as fixed one `InputEditExit(this);`

Instead I implemented an event handler for `ApplicationEvents.OnMessage` and it worked

**Comment by danil-kondr2016** [comment] 2024-10-15 05:21
Resolved horizontal scrolling issue

**Comment by kodemeister** [comment] 2024-10-16 13:50
Fixed by #24

**Closed by kodemeister** 2024-10-16 13:50 UTC
Labels: bug
